name: CI

# Trigger workflow on push or pull request to main
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      MONGO_URI_TEST: ${{ secrets.MONGO_URI_TEST }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      SALT: ${{ secrets.SALT }}

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # 3. Cache node_modules for faster builds
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 5. Run lint (optional)
      - name: Run lint
        run: npm run lint || echo "Lint warnings, not failing workflow"

      # 6. Run tests
      - name: Run tests
        run: npm test

      # 7. Optionally, run build
      - name: Build project
        run: npm run build
